Repository genexuslabs/reporting-controls-library, pull requests merged in 2023-09, with the labels that each got.

#33 Add a warning to enforce the naming convention
  .eslintrc.js
Labels: documentation

#31 Add support for timeline chart
  package-lock.json
  package.json
  src/common/basic-types.ts
  src/components/query-viewer-chart/controller/chart-types.ts
  src/components/query-viewer-chart/controller/highcharts-options.ts
  src/components/query-viewer-chart/controller/processDataAndMetadata.ts
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.scss
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.tsx
  src/components/query-viewer-chart/query-viewer-chart.tsx
  src/components/query-viewer-slider/query-viewer-slider.tsx
Labels: feature

#34 Add support for plotSeries property
  src/common/basic-types.ts
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.scss
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.tsx
  src/components/query-viewer-chart/query-viewer-chart.scss
  src/components/query-viewer-chart/query-viewer-chart.tsx
  src/components/query-viewer-slider/query-viewer-slider.scss
Labels: feature

#35 Fix plotSeries runtime update
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.scss
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.tsx
Labels: fix

#36 Fixes for GxQuery Services implementation
  src/common/basic-types.ts
  src/components.d.ts
  src/components/query-viewer-card/controller/readme.md
  src/components/query-viewer-chart/controller/readme.md
  src/components/query-viewer-chart/readme.md
  src/components/query-viewer-slider/readme.md
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.tsx
  src/components/query-viewer/readme.md
  src/services/gxquery-connector.ts
  src/services/services-manager.ts
  src/services/types/service-result.ts
Labels: fix
