Repository genexuslabs/reporting-controls-library, pull requests merged in 2023-12, with the labels that each got.

#39 Bump reporting-api from ^0.1.3 to ~0.3.0
  package-lock.json
  package.json
Labels: broken

#40 Feature/gx pivot table
  package.json
  src/common/basic-types.ts
  src/components/gx-query/query-render/query-render.tsx
  src/components/gx-query/query-render/readme.md
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.scss
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/controller/readme.md
  src/components/query-viewer-pivot-table/query-viewer-pivot.scss
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer-pivot-table/readme.md
  src/components/query-viewer-table/controller/query-viewer-table-render.scss
  src/components/query-viewer-table/controller/query-viewer-table-render.tsx
  src/components/query-viewer-table/controller/readme.md
  src/components/query-viewer-table/query-viewer-table.scss
  src/components/query-viewer-table/query-viewer-table.tsx
  src/components/query-viewer-table/readme.md
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.tsx
  src/components/query-viewer/readme.md
  src/components/query-viewer/utils.ts
  src/global/types.ts
  src/utils/general.ts
Labels: feature

#41 Fixes for Pivot Table and Angular Generator integration
  package-lock.json
  package.json
  src/components.d.ts
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.scss
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-table/controller/query-viewer-table-render.tsx
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/query-viewer.scss
  src/components/query-viewer/query-viewer.tsx
  src/components/query-viewer/readme.md
  src/components/query-viewer/utils.ts
  stencil.config.ts
  tsconfig.json
Labels: fix
