Repository genexuslabs/reporting-controls-library, pull requests merged in 2024-03, with the labels that each got.

#58 Update reporting-api to version 2.3.3
  package-lock.json
  package.json
Labels: dependencies

#59 Fixes for table output
  src/components.d.ts
  src/components/gx-query/query-render/query-render.tsx
  src/components/gx-query/query-render/readme.md
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/controller/readme.md
  src/components/query-viewer-pivot-table/query-viewer-pivot.scss
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer-pivot-table/readme.md
  src/components/query-viewer/query-viewer.tsx
  src/components/query-viewer/readme.md
Labels: fix

#60 Update api to version v2.3.5
  package-lock.json
  package.json
Labels: dependencies, target: patch

#62 Feature/remove react output
  package-lock.json
  package.json
  src/components/gx-query/query-menu/__test__/query-menu.e2e.ts
  src/components/query-viewer/query-viewer.scss
  src/components/query-viewer/query-viewer.stories.ts
  stencil.config.ts
Labels: fix, dependencies, target: patch, refactoring

#61 Fixes for Table output
  package-lock.json
  package.json
  src/components.d.ts
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.tsx
Labels: fix

#63 Fixes for gx-pivot
  package.json
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer/query-viewer.tsx
Labels: fix, target: patch

#65 Disable PivotTable and Table in GeneXus' applications
  src/components/query-viewer/controller/query-viewer-controller.tsx
Labels: risky, target: patch
