Repository genexuslabs/reporting-controls-library, pull requests merged in 2024-02, with the labels that each got.

#46 Some fixes for Pivot Table output
  package.json
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer/query-viewer.tsx
Labels: fix

#48 Fix/pivot u8
  src/components/gx-query/query-chat/query-chat.tsx
  src/components/gx-query/query-menu/query-menu.tsx
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/query-viewer.tsx
Labels: fix

#49 Connect with saia token
  .env.sample
  .github/workflows/install-and-deploy.yml
  .github/workflows/node.js.yml
  .github/workflows/npmpublish.yml
  package-lock.json
  package.json
  src/common/basic-types.ts
  src/components.d.ts
  src/components/gx-query/query-chat/query-chat.tsx
  src/components/gx-query/query-chat/readme.md
  src/components/gx-query/query-menu-item/query-menu-item.stories.ts
  src/components/gx-query/query-menu-item/query-menu-item.tsx
  src/components/gx-query/query-menu/__test__/query-menu.e2e.ts
  src/components/gx-query/query-menu/__test__/query-menu.spec.tsx
  src/components/gx-query/query-menu/query-menu.tsx
  src/components/gx-query/query-menu/readme.md
  src/components/gx-query/query-render/query-render.tsx
  src/components/gx-query/query-render/readme.md
  src/components/query-viewer-card/controller/card-utils.ts
  src/components/query-viewer-card/controller/query-viewer-card-controller.tsx
  src/components/query-viewer-card/controller/readme.md
  src/components/query-viewer-card/query-viewer-card.stories.ts
  src/components/query-viewer-card/query-viewer-card.tsx
  src/components/query-viewer-chart/controller/chart-types.ts
  src/components/query-viewer-chart/controller/chart-utils.ts
  src/components/query-viewer-chart/controller/highcharts-options.ts
  src/components/query-viewer-chart/controller/processDataAndMetadata.ts
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.tsx
  src/components/query-viewer-chart/controller/readme.md
  src/components/query-viewer-chart/controller/utils-deprecated.ts
  src/components/query-viewer-chart/query-viewer-chart.stories.ts
  src/components/query-viewer-chart/query-viewer-chart.tsx
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/controller/readme.md
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer-pivot-table/readme.md
  src/components/query-viewer-slider/query-viewer-slider.tsx
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.stories.ts
  src/components/query-viewer/query-viewer.tsx
  src/components/query-viewer/readme.md
  src/components/query-viewer/utils.ts
  src/env.d.ts
  src/global/types.ts
  src/index.html
  src/utils/general.ts
Labels: documentation, feature, fix, dependencies, risky, target: minor, refactoring

#53 Correct a spelling mistake
  src/components/query-viewer/query-viewer.tsx
Labels: fix

#52 fix build of pivottable using gxquery
  package-lock.json
  package.json
  src/components.d.ts
  src/components/gx-query/query-chat/readme.md
  src/components/gx-query/query-menu/readme.md
  src/components/gx-query/query-render/readme.md
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.stories.ts
  src/env.d.ts
Labels: dependencies, target: minor

#54 Bump reporting-api from 2.3.1 to 2.3.2
  package.json
Labels: fix, dependencies

#55 Fix for attribute values errors
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
  src/components/query-viewer/query-viewer.tsx
Labels: fix

#56 Fix for Table outputs
  src/components.d.ts
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/controller/readme.md
  src/components/query-viewer-pivot-table/readme.md
Labels: fix
