Repository genexuslabs/reporting-controls-library, pull requests merged in 2024-05, with the labels that each got.

#87 Fix attributeValues to qv with Default type
  src/components/query-viewer/controller/query-viewer-controller.tsx
Labels: fix, target: patch

#88 Fix sort list in pivot table
  package-lock.json
  package.json
Labels: fix, dependencies, target: patch

#89 Bump jspivottable from 1.3.4 to 1.3.6
  package-lock.json
  package.json
Labels: fix, target: patch

#90 Avoid refresh of the table after apply filters
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
Labels: fix, risky, target: patch, refactoring

#91 Improve style of table filters
  package-lock.json
  package.json
  src/components/query-viewer-pivot-table/query-viewer-pivot.scss
Labels: feature, dependencies, target: patch

#92 Remove PivotTable/Table outputs from GeneXus v18u10
  src/components/query-viewer/controller/query-viewer-controller.tsx
Labels: target: patch

#93 Re-enable PivotTable/Table outputs
  src/components/query-viewer/controller/query-viewer-controller.tsx
Labels: fix

#94 Update TypeScript output to ES2022
  tsconfig.json
Labels: feature

#95 Update to Stencil 4 and mark `@genexus/web-controls-library` as a peerDependency
  package-lock.json
  package.json
  src/components.d.ts
  src/components/gx-query/query-chat/query-chat.tsx
  src/components/gx-query/query-menu-item/query-menu-item.tsx
  src/components/gx-query/query-menu/readme.md
  src/components/gx-query/query-render/readme.md
  src/components/query-viewer-chart/controller/readme.md
  src/components/query-viewer-chart/readme.md
  src/components/query-viewer-pivot-table/controller/readme.md
  src/components/query-viewer-pivot-table/readme.md
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/readme.md
  src/index.ts
Labels: feature, dependencies

#96 Improve font inheritance in chart output
  src/components/query-viewer-chart/query-viewer-chart.scss
Labels: fix

#97 Improve customization in the card and chart by adding and exporting parts
  src/components/query-viewer-card/controller/query-viewer-card-controller.tsx
  src/components/query-viewer-card/query-viewer-card.tsx
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.tsx
Labels: feature, target: minor

#98 Remove index.ts file since it was provoking issues with the web-controls-library as peerDependency
  src/components/gx-floating-window/readme.md
  src/components/gx-query/query-chat/readme.md
  src/components/gx-query/query-menu-item/readme.md
  src/components/gx-query/query-menu/readme.md
  src/components/gx-query/query-render/readme.md
  src/components/query-viewer-card/controller/readme.md
  src/components/query-viewer-card/readme.md
  src/components/query-viewer-chart/controller/readme.md
  src/components/query-viewer/readme.md
  src/index.html
  src/index.ts
Labels: fix, target: patch
