Repository genexuslabs/reporting-controls-library, pull requests merged in 2024-04, with the labels that each got.

#67 Make white-label the pivot control and fix style's issues
  src/components/query-viewer-pivot-table/query-viewer-pivot.scss
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
Labels: feature

#68 Re-enable Pivot Table control in GeneXus' applications
  src/components/query-viewer/controller/query-viewer-controller.tsx
Labels: fix

#66 feature / default output type
  package-lock.json
  package.json
  src/components/gx-query/query-render/query-render.tsx
  src/components/query-viewer-slider/query-viewer-slider.stories.ts
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.tsx
  src/components/query-viewer/readme.md
  stencil.config.ts
Labels: feature, risky, target: minor, refactoring

#70 Replace property MetadataName to MetadataId
  package-lock.json
  package.json
  src/components.d.ts
  src/components/gx-query/query-chat/query-chat.tsx
  src/components/gx-query/query-chat/readme.md
  src/components/gx-query/query-menu/query-menu.tsx
  src/components/gx-query/query-menu/readme.md
  src/components/query-viewer-pivot-table/readme.md
  src/components/query-viewer-slider/query-viewer-slider.stories.ts
  src/components/query-viewer/controller/query-viewer-controller.tsx
  src/components/query-viewer/controller/readme.md
  src/components/query-viewer/query-viewer.stories.ts
  src/env.d.ts
Labels: feature, dependencies, target: minor, performance

#71 Fix for multiple Pivot Table controls not working on the same page
  package-lock.json
  package.json
Labels: fix, dependencies, risky

#72 WA for table issues
  src/components/query-viewer-pivot-table/controller/query-viewer-pivot-render.tsx
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
Labels: fix

#73 WA for pivot table title
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
Labels: fix

#75 Fix for restore default view in Table output
  package-lock.json
  package.json
  src/components/query-viewer/query-viewer.tsx
Labels: fix

#76 Fix paging reactivity for PivotTable
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
Labels: fix

#77 Fix for applying filters in Table columns
  package-lock.json
  package.json
  src/components/query-viewer/query-viewer.tsx
Labels: fix, target: patch

#79 Fixed table paging when requested the last page or the previous page
  package-lock.json
  package.json
Labels: fix, target: patch

#78 WA for the GroupBy's comboBox in the timeline, it has been disabled due to functionality issues
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.scss
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.tsx
Labels: fix

#81 Improve the styles of the timeline header
  src/components/query-viewer-chart/controller/query-viewer-chart-controller.scss
Labels: fix

#82 Fix don't display the title div if the title is undefined
  src/components/query-viewer-pivot-table/query-viewer-pivot.tsx
Labels: fix

#83 Upgrade jspivottable version
  package-lock.json
  package.json
Labels: dependencies
